# -*- coding: utf-8 -*-
"""week2_internship.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I2CpsP8d83aO9siCbPxhbE9qnc8-VypA

**KNN model using Iris Dataset**
"""

from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
df = pd.DataFrame(data = iris.data, columns=iris.feature_names)
df['species'] = iris.target
print(df.head(150))
print(df.info())
print(df.describe())

import seaborn as sns
import matplotlib.pyplot as plt

sns.pairplot(df, hue='species')
plt.show()

from sklearn.preprocessing import StandardScaler
# X = just the 4 numerical feature columns
X = df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']]

# y = the target species column (the answer key)
y = df['species']

# 1. Initialize the tool
scaler = StandardScaler()

# 2. Calculate patterns AND transform the data in one shot
X_scaled = scaler.fit_transform(X)

print(X_scaled[0:10])

df_normalized = pd.DataFrame(data=X_scaled,columns=iris.feature_names)
df_normalized['species'] = y

sns.pairplot(df_normalized, hue='species')
plt.show()

df_normalized

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

X_train,X_test,y_train,y_test = train_test_split(X_scaled, y, test_size = 0.3, random_state = 42, stratify = y)

model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train,y_train)
predict_X = model.predict(X_test) # y_test contain actual results of the predict_X

# Generate and plot the confusion matrix
ConfusionMatrixDisplay.from_estimator(
    model,
    X_test,
    y_test,
    display_labels=iris.target_names, # Shows actual species names instead of 0, 1, 2
    cmap=plt.cm.Blues
)

plt.title("KNN Confusion Matrix on Iris Test Data")
plt.show()

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# accuracy
accuracy = accuracy_score(y_test, predict_X)
print('Accuracy: ', accuracy)

# precision
precision = precision_score(y_test, predict_X, average='macro') #  average='macro' used for the multiclass dataset like Iris dataset
print('Precision: ', precision)

# recall
recall = recall_score(y_test, predict_X, average='macro')
print('Recall: ', recall)

# F1_Score
f1 = f1_score(y_test, predict_X, average='macro')
print('F1 Score: ', f1)

"""**Now Testing the model with different datasets**"""

confusing_data = pd.DataFrame([
    [6.0, 3.0, 4.8, 1.8],
    [6.7, 3.0, 5.0, 1.7],
    [4.9, 2.5, 4.5, 1.7],
    [6.0, 2.7, 5.1, 1.6],
    [5.9, 3.2, 4.8, 1.8],
    [5.0, 2.3, 3.3, 1.0]
], columns=iris.feature_names)

true_labels = [2, 1, 2, 1, 2, 1]
scaled_data = scaler.transform(confusing_data)

df = pd.DataFrame(scaled_data,columns=confusing_data.columns)
df

predicted = model.predict(scaled_data)
print(predicted)

display_names = ['versicolor', 'virginica']

# Generate and plot the matrix from your predictions
ConfusionMatrixDisplay.from_predictions(
    true_labels,
    predicted,
    display_labels=display_names,
    cmap=plt.cm.Oranges  # A warm color scheme to highlight any mistakes
)

plt.title("Confusion Matrix for Borderline Iris Samples")
plt.show()

"""2 represents versicolor and 1 represents virginica in the true labels. Hence there are 3 versicolor and 2 virginica

In the above confusion matrix it shows that model predicted 2 versicolor correctly but it predicted virginica specy wrongly
"""